### ISSUE TITLE
[request] Use docs rather than doc as :target-base-path default value to support GitHub pages rendering

### ISSUE THREAD

**Issue by jr0cket** [scicloj/notespace#47]
GitHub pages can render content from the root or `/docs` directory of any repository.  If notespace render static html pages directly to the `docs` directory by default, then files would not need to move location after they are created.

Currently notespace uses `doc` directory as the default location, when calling `(notespace.api/render-static-html)`

`(notespace.state/sub-get-in :config :target-base-path)` returns the value of `doc`

Value seems to be set in https://github.com/scicloj/notespace/blob/master/src/notespace/defaults.clj#L6

Using `(notespace/render-static-html "docs/chapter-name.html")` will generate a new html file in the `docs` directory with the given name.

If the default `:config` value for `:target-base-path` is set to `docs`, then I assume that would default to the `docs` directory if not path is specified when calling `render-static-html`.

**Comment by daslu** [comment]
Thanks @jr0cket. Let us think. Here are a few things to have in mind while we discuss this:

* Projects created by `lein new` have `doc` rather than `docs` -- that is why I chaged the default to be `doc` a while ago.

* There are a few (probably not a lot) users that might be relying on the current behavior (e.g., Notespace itself). This change will require some adaptation at these projects.

* The `target-base-path` can be configured:
```clj
(api/update-config
 #(assoc % :target-base-path "docs"))
```

**Comment by daslu** [comment]
Related discussion:
https://clojurians.zulipchat.com/#narrow/stream/224153-notespace-dev/topic/suggested.20breaking.20change.20in.20default.20target.20path

Since there were no objections, we will do as @jr0cket suggested and adapt where necessary.
